create table if not exists prets_inter_boutiques (
  id bigint generated by default as identity primary key,
  boutique_preteuse_id bigint not null references boutiques(id),
  boutique_emprunteuse_id bigint not null references boutiques(id),
  produit_preteur_id bigint not null references products(id),
  produit_emprunteur_id bigint not null references products(id),
  nom_produit text,
  quantite integer not null,
  statut text not null default 'en_cours',
  date_remboursement timestamptz,
  created_at timestamptz not null default now()
);

create index if not exists idx_prets_statut on prets_inter_boutiques (statut);
