create table if not exists factures_attente (
  id bigint generated by default as identity primary key,
  boutique_id bigint not null references boutiques(id) on delete cascade,
  fournisseur_id uuid not null references fournisseurs(id) on delete cascade,
  reference_facture text not null,
  lignes jsonb not null,
  montant_total numeric not null default 0,
  statut text not null default 'en_attente',
  cree_par_employe_id bigint references employes(id),
  cree_par_nom text,
  traite_par_employe_id bigint references employes(id),
  traite_le timestamptz,
  created_at timestamptz not null default now()
);

create index if not exists idx_factures_attente_boutique_statut on factures_attente (boutique_id, statut);
