create table if not exists pointages (
  id bigint generated by default as identity primary key,
  employe_id bigint not null references employes(id) on delete cascade,
  boutique_id bigint not null references boutiques(id) on delete cascade,
  date date not null default current_date,
  heure_arrivee timestamptz,
  heure_depart timestamptz,
  created_at timestamptz not null default now(),
  unique (employe_id, date)
);

create index if not exists idx_pointages_employe_date on pointages (employe_id, date);
